import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { getBlock, upsertBlock, getClient } from '../db.js';
import { handleRemember } from './memory-ops.js';
import type { Block } from '../bsp.js';

/**
 * pscale_evolution — substrate-level migrations.
 *
 * When the pscale substrate evolves (bug fixes in compaction, new
 * conventions, new block shapes), existing stored state may need to be
 * rebuilt under the new semantic. Rather than silent auto-migration
 * (fragile) or a growing thicket of *_repair tools (clutters the tool
 * surface), this single tool holds the operations. Agents opt in once
 * per known substrate change.
 *
 * Current operations:
 *   remember_migrate — Rebuilds a history block under the 2026-04-23
 *     growth-invariant fix. The pre-fix pscale_remember had a bug where
 *     the second root-level compaction overwrote the nested subtree from
 *     the first, destroying memories 1-9 once you crossed entry 19.
 *     This operation walks the current (possibly damaged) block,
 *     extracts every string at a digit position in depth-first order,
 *     and re-runs them through the fixed handleRemember so the tree is
 *     rebuilt correctly. Summaries in the old block (at underscore
 *     positions) are NOT preserved — they were concatenation strings
 *     that get regenerated by the fixed code. Agents with <=9 memories
 *     (floor-1, no compaction has run) don't need this op; their blocks
 *     are already well-formed.
 *
 * Future operations register here as the substrate evolves. Agents call
 * `pscale_evolution operation=<op_name>` explicitly when they choose to
 * migrate.
 */

interface MigrationResult {
  operation: string;
  agent_id: string;
  status: 'migrated' | 'noop' | 'error';
  memories_recovered?: number;
  backup_block?: string;
  notes?: string;
}

/**
 * Extract every string at a digit position in the block, in chronological
 * order. Two cases matter:
 *   - Post-bug damaged shape: older memories live nested under _ (the
 *     supernested remnants of a pre-fix compaction), newer at root digits.
 *     So _ is visited BEFORE digits.
 *   - Clean new-algorithm shape: _ chain is empty, chronology runs
 *     left-to-right through digits. Visiting _ first is a noop.
 * Either way, ordering ends up chronological. Summary strings (at _ chain
 * terminations) are skipped — the fixed remember regenerates summaries.
 */
function extractMemoriesInOrder(block: Block): string[] {
  const out: string[] = [];
  function walk(node: any): void {
    if (!node || typeof node !== 'object') return;
    // _ first: older content (from pre-fix supernest OR empty chain)
    if (node._ && typeof node._ === 'object') walk(node._);
    // Then digits in order: newer content
    for (const d of '123456789') {
      if (!(d in node)) continue;
      const v = node[d];
      if (typeof v === 'string') out.push(v);
      else if (typeof v === 'object') walk(v);
    }
  }
  walk(block);
  return out;
}

/** Check if a block is "at-risk" of pre-fix damage. */
function needsMigration(block: Block): { needs: boolean; reason: string } {
  if (!block || Object.keys(block).length === 0) return { needs: false, reason: 'empty block' };
  // Shape check: if _ chain is a string AND block has any digit children, it's floor-1.
  // If floor-1 and <= 9 digit children present, no migration needed.
  if (typeof block._ === 'string' || block._ === undefined) {
    return { needs: false, reason: 'floor-1 shape — pre-compaction, no migration needed' };
  }
  // floor >= 2. Check for the pre-fix damage signature: are any digit children at root strings?
  // In the new algorithm, floor-2+ root digits hold OBJECTS (batches). If any are strings, that's the
  // old-bug shape (root digit set to a bare string by the post-compaction handler).
  for (const d of '123456789') {
    if (d in block && typeof block[d] === 'string') {
      return { needs: true, reason: 'pre-fix damage — root has bare string at digit (old supernest shape)' };
    }
  }
  // Also flag if the _ chain's innermost position is an object (should be a string for a proper floor-K block).
  let cursor: any = block._;
  while (cursor && typeof cursor === 'object') {
    if (typeof cursor._ === 'string' || cursor._ === undefined) {
      return { needs: false, reason: 'shape appears consistent with new algorithm' };
    }
    cursor = cursor._;
  }
  return { needs: false, reason: 'shape consistent' };
}

/** Back up the current block under a timestamped name so migration is reversible. */
async function backupBlock(agent_id: string, block: Block): Promise<string> {
  const backupName = `history_pre_evolution_${Date.now()}`;
  await upsertBlock(agent_id, backupName, 'history_backup', block);
  return backupName;
}

async function migrateRemember(agent_id: string, dry_run: boolean): Promise<MigrationResult> {
  const row = await getBlock(agent_id, 'history');
  if (!row) {
    return {
      operation: 'remember_migrate',
      agent_id,
      status: 'noop',
      notes: 'No history block exists. Nothing to migrate.',
    };
  }
  const block = row.block as Block;
  const { needs, reason } = needsMigration(block);
  if (!needs) {
    return {
      operation: 'remember_migrate',
      agent_id,
      status: 'noop',
      notes: `No migration needed: ${reason}`,
    };
  }

  // Extract all memories in order.
  const memories = extractMemoriesInOrder(block);

  if (dry_run) {
    return {
      operation: 'remember_migrate',
      agent_id,
      status: 'noop',
      memories_recovered: memories.length,
      notes: `Dry-run: would migrate ${memories.length} memories. Re-run without dry_run to commit.`,
    };
  }

  // Back up the existing block.
  const backupName = await backupBlock(agent_id, block);

  // Delete the current history block so handleRemember starts fresh.
  const client = getClient();
  const { error: delErr } = await client
    .from('pscale_blocks')
    .delete()
    .eq('owner_id', agent_id)
    .eq('name', 'history');
  if (delErr) {
    return {
      operation: 'remember_migrate',
      agent_id,
      status: 'error',
      notes: `Failed to clear existing block: ${delErr.message}. Backup preserved at ${backupName}.`,
    };
  }

  // Replay memories through the fixed handleRemember. This rebuilds the tree
  // correctly under the 2026-04-23 growth invariant.
  for (const memory of memories) {
    await handleRemember({ agent_id, content: memory });
  }

  return {
    operation: 'remember_migrate',
    agent_id,
    status: 'migrated',
    memories_recovered: memories.length,
    backup_block: backupName,
    notes: `Migrated ${memories.length} memories. Old block preserved as ${backupName} — delete manually with pscale_blocks DELETE once you're satisfied the migration is clean.`,
  };
}

export async function handleEvolution(
  { agent_id, operation, dry_run }: {
    agent_id: string; operation: string; dry_run?: boolean;
  },
) {
  const isDry = dry_run ?? false;
  let result: MigrationResult;

  if (operation === 'remember_migrate') {
    result = await migrateRemember(agent_id, isDry);
  } else {
    result = {
      operation,
      agent_id,
      status: 'error',
      notes: `Unknown operation: ${operation}. Known: remember_migrate.`,
    };
  }

  return {
    content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
  };
}

export function registerEvolutionOps(server: McpServer) {
  server.tool(
    'pscale_evolution',
    `Substrate migration. When pscale itself gains a fix or new convention, stored state for existing agents may need to be rebuilt under the new semantic. This tool holds the migration operations. Agents call it explicitly when they choose to update.

Operations:
  remember_migrate — rebuild your history block under the 2026-04-23 growth-invariant fix. Only needed if your history has >= 19 memories written under the old pscale_remember (the pre-fix tool lost memories 1-9 on the second compaction). Blocks with <= 9 memories are floor-1 and fine as-is.

Always backs up the existing block under a timestamped name (history_pre_evolution_<ts>) before migrating. Supports dry_run=true for preview.`,
    {
      agent_id: z.string().describe('The agent whose substrate is being migrated — typically yourself.'),
      operation: z.enum(['remember_migrate']).describe('Which migration to run. See tool description.'),
      dry_run: z.boolean().optional().describe('If true, report what would happen without writing anything. Default false.'),
    },
    handleEvolution,
  );
}
